---
# tasks file for lamp_compose
- name: telecharge et desarchive wordpress
  unarchive: 
    src: https://wordpress.org/latest.tar.gz
    dest: '{{repertoire_projet}}'
    remote_src: yes
    owner: 1000
    group: 1000

- name: execute le docker-compose
  docker_service:
    project_name: wp_lamp
    definition: 
      version: '2'
      services: 
        apache:
          image: webdevops/php-apache:centos-7
          ports: 
            - "{{APACHE.PORT}}:80"
          volumes: 
            - '{{repertoire_projet}}/wordpress:/app'
          links:
            - mariadb:db
        mariadb: 
          image: centos/mariadb-101-centos7
          ports: 
            - "{{MYSQL.PORT}}:3306"
          environment: 
            - MYSQL_DATABASE={{MYSQL.DATABASE}}
            - MYSQL_USER={{MYSQL.USER}}
            - MYSQL_PASSWORD={{MYSQL.PASSWORD}}
        phpmyadmin: 
          image: phpmyadmin/phpmyadmin
          ports: 
            - "{{PHPMYADMIN.PORT}}:80"
          links: 
            - mariadb:db
